colors.draw_bold_text_with_bright_colors = true
colors.transparent_background_colors = true


[colors.primary]
background = '0x000010'
foreground = '0x0ffffc'


[colors.normal]
black = '0x123e7c'
red = '0xff0050'
green = '0xd300ff'
yellow = '0xffff00'
blue = '0x123e7c'
magenta = '0x711c91'
cyan = '0x0ffffc'
white = '0xd7d7d5'


[colors.bright]
black = '0x1c61c2'
red = '0xff0050'
green = '0xd300ff'
yellow = '0xffff00'
blue = '0x00ff00'
magenta = '0x711c91'
cyan = '0x0ffffc'
white = '0xd7d7d5'


[colors.dim]
black = '0x1c61c2'
red = '0xff0050'
green = '0xd300ff'
yellow = '0xffff00'
blue = '0x123e7c'
magenta = '0x711c91'
cyan = '0x0ffffc'
white = '0xd7d7d5'


[window]
dimensions = { columns = 80, lines = 20 }
position = "None"
padding = { x = 10, y = 5 }
decorations = "None" #hide the title bar
opacity = 0.8

[cursor]
style = { shape = "Block", blinking = "Always" }
